sudo: required

services:
  - docker

before_install:
  - docker build -t Zeshan485/multi-docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true Zeshan485/multi-docker-react npm run test -- --coverage

after_success:
  - docker build -t Zeshan485/multi-docker-client ./client
  - docker build -t Zeshan485/multi-docker-api ./server
  - docker build -t Zeshan485/multi-docker-worker ./worker
  - docker build -t Zeshan485/multi-docker-nginx ./nginx
  
  # Log in to travis ci with my docker credentials
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  # Push these images to docker hub
  - docker push Zeshan485/multi-docker-client
  - docker push Zeshan485/multi-docker-api
  - docker push Zeshan485/multi-docker-worker
  - docker push Zeshan485/multi-docker-nginx