services: 
  
  nginx:
    image: zeshan485/multi-docker-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  server:
    image: zeshan485/multi-docker-api
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  worker:
    image: zeshan485/multi-docker-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  client:
    image: zeshan485/multi-docker-client
    mem_limit: 128m
    hostname: client

